name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
      - run: npm ci --no-audit
      - name: Run lint
      - run: npm run lint --if-present
      - name: Run tests
      - run: npm run test
      - name: Run build
      - run: npm run build --if-present
        env:
          CI: true
